export default {
  title: "Foundations/Icons",
  tags: ["autodocs"],
  parameters: {
    docs: {
      description: {
        component:
          'Ikon KarirKit — token berbasis class, pakai seperti icon font: `<i class="kk kk-house"></i>`. Mewarisi `currentColor`, ukuran diatur lewat utility `h-*`/`w-*`. Setiap ikon tersedia dalam 6 ketebalan (weight): Regular (default, tanpa modifier), Thin, Light, Bold, Fill, dan Duotone — tinggal tambahkan satu class modifier (`kk-thin`, `kk-light`, `kk-bold`, `kk-fill`, `kk-duotone`) di samping `kk-{nama}`.',
      },
    },
  },
};

// Seluruh 1.512 ikon Phosphor Icons yang tersedia di src/input.css (token
// --icon-*, lihat @theme), masing-masing dengan 6 varian weight. Regenerate
// dari assets/icons/regular/*.svg kalau katalog Phosphor Icons di-upgrade,
// jangan tambah manual satu-satu.
const ICONS = [
  ["kk-acorn", "acorn"],
  ["kk-address-book", "address book"],
  ["kk-address-book-tabs", "address book tabs"],
  ["kk-air-traffic-control", "air traffic control"],
  ["kk-airplane", "airplane"],
  ["kk-airplane-in-flight", "airplane in flight"],
  ["kk-airplane-landing", "airplane landing"],
  ["kk-airplane-takeoff", "airplane takeoff"],
  ["kk-airplane-taxiing", "airplane taxiing"],
  ["kk-airplane-tilt", "airplane tilt"],
  ["kk-airplay", "airplay"],
  ["kk-alarm", "alarm"],
  ["kk-alien", "alien"],
  ["kk-align-bottom", "align bottom"],
  ["kk-align-bottom-simple", "align bottom simple"],
  ["kk-align-center-horizontal", "align center horizontal"],
  ["kk-align-center-horizontal-simple", "align center horizontal simple"],
  ["kk-align-center-vertical", "align center vertical"],
  ["kk-align-center-vertical-simple", "align center vertical simple"],
  ["kk-align-left", "align left"],
  ["kk-align-left-simple", "align left simple"],
  ["kk-align-right", "align right"],
  ["kk-align-right-simple", "align right simple"],
  ["kk-align-top", "align top"],
  ["kk-align-top-simple", "align top simple"],
  ["kk-amazon-logo", "amazon logo"],
  ["kk-ambulance", "ambulance"],
  ["kk-anchor", "anchor"],
  ["kk-anchor-simple", "anchor simple"],
  ["kk-android-logo", "android logo"],
  ["kk-angle", "angle"],
  ["kk-angular-logo", "angular logo"],
  ["kk-aperture", "aperture"],
  ["kk-app-store-logo", "app store logo"],
  ["kk-app-window", "app window"],
  ["kk-apple-logo", "apple logo"],
  ["kk-apple-podcasts-logo", "apple podcasts logo"],
  ["kk-approximate-equals", "approximate equals"],
  ["kk-archive", "archive"],
  ["kk-armchair", "armchair"],
  ["kk-arrow-arc-left", "arrow arc left"],
  ["kk-arrow-arc-right", "arrow arc right"],
  ["kk-arrow-bend-double-up-left", "arrow bend double up left"],
  ["kk-arrow-bend-double-up-right", "arrow bend double up right"],
  ["kk-arrow-bend-down-left", "arrow bend down left"],
  ["kk-arrow-bend-down-right", "arrow bend down right"],
  ["kk-arrow-bend-left-down", "arrow bend left down"],
  ["kk-arrow-bend-left-up", "arrow bend left up"],
  ["kk-arrow-bend-right-down", "arrow bend right down"],
  ["kk-arrow-bend-right-up", "arrow bend right up"],
  ["kk-arrow-bend-up-left", "arrow bend up left"],
  ["kk-arrow-bend-up-right", "arrow bend up right"],
  ["kk-arrow-circle-down", "arrow circle down"],
  ["kk-arrow-circle-down-left", "arrow circle down left"],
  ["kk-arrow-circle-down-right", "arrow circle down right"],
  ["kk-arrow-circle-left", "arrow circle left"],
  ["kk-arrow-circle-right", "arrow circle right"],
  ["kk-arrow-circle-up", "arrow circle up"],
  ["kk-arrow-circle-up-left", "arrow circle up left"],
  ["kk-arrow-circle-up-right", "arrow circle up right"],
  ["kk-arrow-clockwise", "arrow clockwise"],
  ["kk-arrow-counter-clockwise", "arrow counter clockwise"],
  ["kk-arrow-down", "arrow down"],
  ["kk-arrow-down-left", "arrow down left"],
  ["kk-arrow-down-right", "arrow down right"],
  ["kk-arrow-elbow-down-left", "arrow elbow down left"],
  ["kk-arrow-elbow-down-right", "arrow elbow down right"],
  ["kk-arrow-elbow-left", "arrow elbow left"],
  ["kk-arrow-elbow-left-down", "arrow elbow left down"],
  ["kk-arrow-elbow-left-up", "arrow elbow left up"],
  ["kk-arrow-elbow-right", "arrow elbow right"],
  ["kk-arrow-elbow-right-down", "arrow elbow right down"],
  ["kk-arrow-elbow-right-up", "arrow elbow right up"],
  ["kk-arrow-elbow-up-left", "arrow elbow up left"],
  ["kk-arrow-elbow-up-right", "arrow elbow up right"],
  ["kk-arrow-fat-down", "arrow fat down"],
  ["kk-arrow-fat-left", "arrow fat left"],
  ["kk-arrow-fat-line-down", "arrow fat line down"],
  ["kk-arrow-fat-line-left", "arrow fat line left"],
  ["kk-arrow-fat-line-right", "arrow fat line right"],
  ["kk-arrow-fat-line-up", "arrow fat line up"],
  ["kk-arrow-fat-lines-down", "arrow fat lines down"],
  ["kk-arrow-fat-lines-left", "arrow fat lines left"],
  ["kk-arrow-fat-lines-right", "arrow fat lines right"],
  ["kk-arrow-fat-lines-up", "arrow fat lines up"],
  ["kk-arrow-fat-right", "arrow fat right"],
  ["kk-arrow-fat-up", "arrow fat up"],
  ["kk-arrow-left", "arrow left"],
  ["kk-arrow-line-down", "arrow line down"],
  ["kk-arrow-line-down-left", "arrow line down left"],
  ["kk-arrow-line-down-right", "arrow line down right"],
  ["kk-arrow-line-left", "arrow line left"],
  ["kk-arrow-line-right", "arrow line right"],
  ["kk-arrow-line-up", "arrow line up"],
  ["kk-arrow-line-up-left", "arrow line up left"],
  ["kk-arrow-line-up-right", "arrow line up right"],
  ["kk-arrow-right", "arrow right"],
  ["kk-arrow-square-down", "arrow square down"],
  ["kk-arrow-square-down-left", "arrow square down left"],
  ["kk-arrow-square-down-right", "arrow square down right"],
  ["kk-arrow-square-in", "arrow square in"],
  ["kk-arrow-square-left", "arrow square left"],
  ["kk-arrow-square-out", "arrow square out"],
  ["kk-arrow-square-right", "arrow square right"],
  ["kk-arrow-square-up", "arrow square up"],
  ["kk-arrow-square-up-left", "arrow square up left"],
  ["kk-arrow-square-up-right", "arrow square up right"],
  ["kk-arrow-u-down-left", "arrow u down left"],
  ["kk-arrow-u-down-right", "arrow u down right"],
  ["kk-arrow-u-left-down", "arrow u left down"],
  ["kk-arrow-u-left-up", "arrow u left up"],
  ["kk-arrow-u-right-down", "arrow u right down"],
  ["kk-arrow-u-right-up", "arrow u right up"],
  ["kk-arrow-u-up-left", "arrow u up left"],
  ["kk-arrow-u-up-right", "arrow u up right"],
  ["kk-arrow-up", "arrow up"],
  ["kk-arrow-up-left", "arrow up left"],
  ["kk-arrow-up-right", "arrow up right"],
  ["kk-arrows-clockwise", "arrows clockwise"],
  ["kk-arrows-counter-clockwise", "arrows counter clockwise"],
  ["kk-arrows-down-up", "arrows down up"],
  ["kk-arrows-horizontal", "arrows horizontal"],
  ["kk-arrows-in", "arrows in"],
  ["kk-arrows-in-cardinal", "arrows in cardinal"],
  ["kk-arrows-in-line-horizontal", "arrows in line horizontal"],
  ["kk-arrows-in-line-vertical", "arrows in line vertical"],
  ["kk-arrows-in-simple", "arrows in simple"],
  ["kk-arrows-left-right", "arrows left right"],
  ["kk-arrows-merge", "arrows merge"],
  ["kk-arrows-out", "arrows out"],
  ["kk-arrows-out-cardinal", "arrows out cardinal"],
  ["kk-arrows-out-line-horizontal", "arrows out line horizontal"],
  ["kk-arrows-out-line-vertical", "arrows out line vertical"],
  ["kk-arrows-out-simple", "arrows out simple"],
  ["kk-arrows-split", "arrows split"],
  ["kk-arrows-vertical", "arrows vertical"],
  ["kk-article", "article"],
  ["kk-article-medium", "article medium"],
  ["kk-article-ny-times", "article ny times"],
  ["kk-asclepius", "asclepius"],
  ["kk-asterisk", "asterisk"],
  ["kk-asterisk-simple", "asterisk simple"],
  ["kk-at", "at"],
  ["kk-atom", "atom"],
  ["kk-avocado", "avocado"],
  ["kk-axe", "axe"],
  ["kk-baby", "baby"],
  ["kk-baby-carriage", "baby carriage"],
  ["kk-backpack", "backpack"],
  ["kk-backspace", "backspace"],
  ["kk-bag", "bag"],
  ["kk-bag-simple", "bag simple"],
  ["kk-balloon", "balloon"],
  ["kk-bandaids", "bandaids"],
  ["kk-bank", "bank"],
  ["kk-barbell", "barbell"],
  ["kk-barcode", "barcode"],
  ["kk-barn", "barn"],
  ["kk-barricade", "barricade"],
  ["kk-baseball", "baseball"],
  ["kk-baseball-cap", "baseball cap"],
  ["kk-baseball-helmet", "baseball helmet"],
  ["kk-basket", "basket"],
  ["kk-basketball", "basketball"],
  ["kk-bathtub", "bathtub"],
  ["kk-battery-charging", "battery charging"],
  ["kk-battery-charging-vertical", "battery charging vertical"],
  ["kk-battery-empty", "battery empty"],
  ["kk-battery-full", "battery full"],
  ["kk-battery-high", "battery high"],
  ["kk-battery-low", "battery low"],
  ["kk-battery-medium", "battery medium"],
  ["kk-battery-plus", "battery plus"],
  ["kk-battery-plus-vertical", "battery plus vertical"],
  ["kk-battery-vertical-empty", "battery vertical empty"],
  ["kk-battery-vertical-full", "battery vertical full"],
  ["kk-battery-vertical-high", "battery vertical high"],
  ["kk-battery-vertical-low", "battery vertical low"],
  ["kk-battery-vertical-medium", "battery vertical medium"],
  ["kk-battery-warning", "battery warning"],
  ["kk-battery-warning-vertical", "battery warning vertical"],
  ["kk-beach-ball", "beach ball"],
  ["kk-beanie", "beanie"],
  ["kk-bed", "bed"],
  ["kk-beer-bottle", "beer bottle"],
  ["kk-beer-stein", "beer stein"],
  ["kk-behance-logo", "behance logo"],
  ["kk-bell", "bell"],
  ["kk-bell-ringing", "bell ringing"],
  ["kk-bell-simple", "bell simple"],
  ["kk-bell-simple-ringing", "bell simple ringing"],
  ["kk-bell-simple-slash", "bell simple slash"],
  ["kk-bell-simple-z", "bell simple z"],
  ["kk-bell-slash", "bell slash"],
  ["kk-bell-z", "bell z"],
  ["kk-belt", "belt"],
  ["kk-bezier-curve", "bezier curve"],
  ["kk-bicycle", "bicycle"],
  ["kk-binary", "binary"],
  ["kk-binoculars", "binoculars"],
  ["kk-biohazard", "biohazard"],
  ["kk-bird", "bird"],
  ["kk-blueprint", "blueprint"],
  ["kk-bluetooth", "bluetooth"],
  ["kk-bluetooth-connected", "bluetooth connected"],
  ["kk-bluetooth-slash", "bluetooth slash"],
  ["kk-bluetooth-x", "bluetooth x"],
  ["kk-boat", "boat"],
  ["kk-bomb", "bomb"],
  ["kk-bone", "bone"],
  ["kk-book", "book"],
  ["kk-book-bookmark", "book bookmark"],
  ["kk-book-open", "book open"],
  ["kk-book-open-text", "book open text"],
  ["kk-book-open-user", "book open user"],
  ["kk-bookmark", "bookmark"],
  ["kk-bookmark-simple", "bookmark simple"],
  ["kk-bookmarks", "bookmarks"],
  ["kk-bookmarks-simple", "bookmarks simple"],
  ["kk-books", "books"],
  ["kk-boot", "boot"],
  ["kk-boules", "boules"],
  ["kk-bounding-box", "bounding box"],
  ["kk-bowl-food", "bowl food"],
  ["kk-bowl-steam", "bowl steam"],
  ["kk-bowling-ball", "bowling ball"],
  ["kk-box-arrow-down", "box arrow down"],
  ["kk-box-arrow-up", "box arrow up"],
  ["kk-boxing-glove", "boxing glove"],
  ["kk-brackets-angle", "brackets angle"],
  ["kk-brackets-curly", "brackets curly"],
  ["kk-brackets-round", "brackets round"],
  ["kk-brackets-square", "brackets square"],
  ["kk-brain", "brain"],
  ["kk-brandy", "brandy"],
  ["kk-bread", "bread"],
  ["kk-bridge", "bridge"],
  ["kk-briefcase", "briefcase"],
  ["kk-briefcase-metal", "briefcase metal"],
  ["kk-broadcast", "broadcast"],
  ["kk-broom", "broom"],
  ["kk-browser", "browser"],
  ["kk-browsers", "browsers"],
  ["kk-bug", "bug"],
  ["kk-bug-beetle", "bug beetle"],
  ["kk-bug-droid", "bug droid"],
  ["kk-building", "building"],
  ["kk-building-apartment", "building apartment"],
  ["kk-building-office", "building office"],
  ["kk-buildings", "buildings"],
  ["kk-bulldozer", "bulldozer"],
  ["kk-bus", "bus"],
  ["kk-butterfly", "butterfly"],
  ["kk-cable-car", "cable car"],
  ["kk-cactus", "cactus"],
  ["kk-cake", "cake"],
  ["kk-calculator", "calculator"],
  ["kk-calendar", "calendar"],
  ["kk-calendar-blank", "calendar blank"],
  ["kk-calendar-check", "calendar check"],
  ["kk-calendar-dot", "calendar dot"],
  ["kk-calendar-dots", "calendar dots"],
  ["kk-calendar-heart", "calendar heart"],
  ["kk-calendar-minus", "calendar minus"],
  ["kk-calendar-plus", "calendar plus"],
  ["kk-calendar-slash", "calendar slash"],
  ["kk-calendar-star", "calendar star"],
  ["kk-calendar-x", "calendar x"],
  ["kk-call-bell", "call bell"],
  ["kk-camera", "camera"],
  ["kk-camera-plus", "camera plus"],
  ["kk-camera-rotate", "camera rotate"],
  ["kk-camera-slash", "camera slash"],
  ["kk-campfire", "campfire"],
  ["kk-car", "car"],
  ["kk-car-battery", "car battery"],
  ["kk-car-profile", "car profile"],
  ["kk-car-simple", "car simple"],
  ["kk-cardholder", "cardholder"],
  ["kk-cards", "cards"],
  ["kk-cards-three", "cards three"],
  ["kk-caret-circle-double-down", "caret circle double down"],
  ["kk-caret-circle-double-left", "caret circle double left"],
  ["kk-caret-circle-double-right", "caret circle double right"],
  ["kk-caret-circle-double-up", "caret circle double up"],
  ["kk-caret-circle-down", "caret circle down"],
  ["kk-caret-circle-left", "caret circle left"],
  ["kk-caret-circle-right", "caret circle right"],
  ["kk-caret-circle-up", "caret circle up"],
  ["kk-caret-circle-up-down", "caret circle up down"],
  ["kk-caret-double-down", "caret double down"],
  ["kk-caret-double-left", "caret double left"],
  ["kk-caret-double-right", "caret double right"],
  ["kk-caret-double-up", "caret double up"],
  ["kk-caret-down", "caret down"],
  ["kk-caret-left", "caret left"],
  ["kk-caret-line-down", "caret line down"],
  ["kk-caret-line-left", "caret line left"],
  ["kk-caret-line-right", "caret line right"],
  ["kk-caret-line-up", "caret line up"],
  ["kk-caret-right", "caret right"],
  ["kk-caret-up", "caret up"],
  ["kk-caret-up-down", "caret up down"],
  ["kk-carrot", "carrot"],
  ["kk-cash-register", "cash register"],
  ["kk-cassette-tape", "cassette tape"],
  ["kk-castle-turret", "castle turret"],
  ["kk-cat", "cat"],
  ["kk-cell-signal-full", "cell signal full"],
  ["kk-cell-signal-high", "cell signal high"],
  ["kk-cell-signal-low", "cell signal low"],
  ["kk-cell-signal-medium", "cell signal medium"],
  ["kk-cell-signal-none", "cell signal none"],
  ["kk-cell-signal-slash", "cell signal slash"],
  ["kk-cell-signal-x", "cell signal x"],
  ["kk-cell-tower", "cell tower"],
  ["kk-certificate", "certificate"],
  ["kk-chair", "chair"],
  ["kk-chalkboard", "chalkboard"],
  ["kk-chalkboard-simple", "chalkboard simple"],
  ["kk-chalkboard-teacher", "chalkboard teacher"],
  ["kk-champagne", "champagne"],
  ["kk-charging-station", "charging station"],
  ["kk-chart-bar", "chart bar"],
  ["kk-chart-bar-horizontal", "chart bar horizontal"],
  ["kk-chart-donut", "chart donut"],
  ["kk-chart-line", "chart line"],
  ["kk-chart-line-down", "chart line down"],
  ["kk-chart-line-up", "chart line up"],
  ["kk-chart-pie", "chart pie"],
  ["kk-chart-pie-slice", "chart pie slice"],
  ["kk-chart-polar", "chart polar"],
  ["kk-chart-scatter", "chart scatter"],
  ["kk-chat", "chat"],
  ["kk-chat-centered", "chat centered"],
  ["kk-chat-centered-dots", "chat centered dots"],
  ["kk-chat-centered-slash", "chat centered slash"],
  ["kk-chat-centered-text", "chat centered text"],
  ["kk-chat-circle", "chat circle"],
  ["kk-chat-circle-dots", "chat circle dots"],
  ["kk-chat-circle-slash", "chat circle slash"],
  ["kk-chat-circle-text", "chat circle text"],
  ["kk-chat-dots", "chat dots"],
  ["kk-chat-slash", "chat slash"],
  ["kk-chat-teardrop", "chat teardrop"],
  ["kk-chat-teardrop-dots", "chat teardrop dots"],
  ["kk-chat-teardrop-slash", "chat teardrop slash"],
  ["kk-chat-teardrop-text", "chat teardrop text"],
  ["kk-chat-text", "chat text"],
  ["kk-chats", "chats"],
  ["kk-chats-circle", "chats circle"],
  ["kk-chats-teardrop", "chats teardrop"],
  ["kk-check", "check"],
  ["kk-check-circle", "check circle"],
  ["kk-check-fat", "check fat"],
  ["kk-check-square", "check square"],
  ["kk-check-square-offset", "check square offset"],
  ["kk-checkerboard", "checkerboard"],
  ["kk-checks", "checks"],
  ["kk-cheers", "cheers"],
  ["kk-cheese", "cheese"],
  ["kk-chef-hat", "chef hat"],
  ["kk-cherries", "cherries"],
  ["kk-church", "church"],
  ["kk-cigarette", "cigarette"],
  ["kk-cigarette-slash", "cigarette slash"],
  ["kk-circle", "circle"],
  ["kk-circle-dashed", "circle dashed"],
  ["kk-circle-half", "circle half"],
  ["kk-circle-half-tilt", "circle half tilt"],
  ["kk-circle-notch", "circle notch"],
  ["kk-circles-four", "circles four"],
  ["kk-circles-three", "circles three"],
  ["kk-circles-three-plus", "circles three plus"],
  ["kk-circuitry", "circuitry"],
  ["kk-city", "city"],
  ["kk-clipboard", "clipboard"],
  ["kk-clipboard-text", "clipboard text"],
  ["kk-clock", "clock"],
  ["kk-clock-afternoon", "clock afternoon"],
  ["kk-clock-clockwise", "clock clockwise"],
  ["kk-clock-countdown", "clock countdown"],
  ["kk-clock-counter-clockwise", "clock counter clockwise"],
  ["kk-clock-user", "clock user"],
  ["kk-closed-captioning", "closed captioning"],
  ["kk-cloud", "cloud"],
  ["kk-cloud-arrow-down", "cloud arrow down"],
  ["kk-cloud-arrow-up", "cloud arrow up"],
  ["kk-cloud-check", "cloud check"],
  ["kk-cloud-fog", "cloud fog"],
  ["kk-cloud-lightning", "cloud lightning"],
  ["kk-cloud-moon", "cloud moon"],
  ["kk-cloud-rain", "cloud rain"],
  ["kk-cloud-slash", "cloud slash"],
  ["kk-cloud-snow", "cloud snow"],
  ["kk-cloud-sun", "cloud sun"],
  ["kk-cloud-warning", "cloud warning"],
  ["kk-cloud-x", "cloud x"],
  ["kk-clover", "clover"],
  ["kk-club", "club"],
  ["kk-coat-hanger", "coat hanger"],
  ["kk-coda-logo", "coda logo"],
  ["kk-code", "code"],
  ["kk-code-block", "code block"],
  ["kk-code-simple", "code simple"],
  ["kk-codepen-logo", "codepen logo"],
  ["kk-codesandbox-logo", "codesandbox logo"],
  ["kk-coffee", "coffee"],
  ["kk-coffee-bean", "coffee bean"],
  ["kk-coin", "coin"],
  ["kk-coin-vertical", "coin vertical"],
  ["kk-coins", "coins"],
  ["kk-columns", "columns"],
  ["kk-columns-plus-left", "columns plus left"],
  ["kk-columns-plus-right", "columns plus right"],
  ["kk-command", "command"],
  ["kk-compass", "compass"],
  ["kk-compass-rose", "compass rose"],
  ["kk-compass-tool", "compass tool"],
  ["kk-computer-tower", "computer tower"],
  ["kk-confetti", "confetti"],
  ["kk-contactless-payment", "contactless payment"],
  ["kk-control", "control"],
  ["kk-cookie", "cookie"],
  ["kk-cooking-pot", "cooking pot"],
  ["kk-copy", "copy"],
  ["kk-copy-simple", "copy simple"],
  ["kk-copyleft", "copyleft"],
  ["kk-copyright", "copyright"],
  ["kk-corners-in", "corners in"],
  ["kk-corners-out", "corners out"],
  ["kk-couch", "couch"],
  ["kk-court-basketball", "court basketball"],
  ["kk-cow", "cow"],
  ["kk-cowboy-hat", "cowboy hat"],
  ["kk-cpu", "cpu"],
  ["kk-crane", "crane"],
  ["kk-crane-tower", "crane tower"],
  ["kk-credit-card", "credit card"],
  ["kk-cricket", "cricket"],
  ["kk-crop", "crop"],
  ["kk-cross", "cross"],
  ["kk-crosshair", "crosshair"],
  ["kk-crosshair-simple", "crosshair simple"],
  ["kk-crown", "crown"],
  ["kk-crown-cross", "crown cross"],
  ["kk-crown-simple", "crown simple"],
  ["kk-cube", "cube"],
  ["kk-cube-focus", "cube focus"],
  ["kk-cube-transparent", "cube transparent"],
  ["kk-currency-btc", "currency btc"],
  ["kk-currency-circle-dollar", "currency circle dollar"],
  ["kk-currency-cny", "currency cny"],
  ["kk-currency-dollar", "currency dollar"],
  ["kk-currency-dollar-simple", "currency dollar simple"],
  ["kk-currency-eth", "currency eth"],
  ["kk-currency-eur", "currency eur"],
  ["kk-currency-gbp", "currency gbp"],
  ["kk-currency-inr", "currency inr"],
  ["kk-currency-jpy", "currency jpy"],
  ["kk-currency-krw", "currency krw"],
  ["kk-currency-kzt", "currency kzt"],
  ["kk-currency-ngn", "currency ngn"],
  ["kk-currency-rub", "currency rub"],
  ["kk-cursor", "cursor"],
  ["kk-cursor-click", "cursor click"],
  ["kk-cursor-text", "cursor text"],
  ["kk-cylinder", "cylinder"],
  ["kk-database", "database"],
  ["kk-desk", "desk"],
  ["kk-desktop", "desktop"],
  ["kk-desktop-tower", "desktop tower"],
  ["kk-detective", "detective"],
  ["kk-dev-to-logo", "dev to logo"],
  ["kk-device-mobile", "device mobile"],
  ["kk-device-mobile-camera", "device mobile camera"],
  ["kk-device-mobile-slash", "device mobile slash"],
  ["kk-device-mobile-speaker", "device mobile speaker"],
  ["kk-device-rotate", "device rotate"],
  ["kk-device-tablet", "device tablet"],
  ["kk-device-tablet-camera", "device tablet camera"],
  ["kk-device-tablet-speaker", "device tablet speaker"],
  ["kk-devices", "devices"],
  ["kk-diamond", "diamond"],
  ["kk-diamonds-four", "diamonds four"],
  ["kk-dice-five", "dice five"],
  ["kk-dice-four", "dice four"],
  ["kk-dice-one", "dice one"],
  ["kk-dice-six", "dice six"],
  ["kk-dice-three", "dice three"],
  ["kk-dice-two", "dice two"],
  ["kk-disc", "disc"],
  ["kk-disco-ball", "disco ball"],
  ["kk-discord-logo", "discord logo"],
  ["kk-divide", "divide"],
  ["kk-dna", "dna"],
  ["kk-dog", "dog"],
  ["kk-door", "door"],
  ["kk-door-open", "door open"],
  ["kk-dot", "dot"],
  ["kk-dot-outline", "dot outline"],
  ["kk-dots-nine", "dots nine"],
  ["kk-dots-six", "dots six"],
  ["kk-dots-six-vertical", "dots six vertical"],
  ["kk-dots-three", "dots three"],
  ["kk-dots-three-circle", "dots three circle"],
  ["kk-dots-three-circle-vertical", "dots three circle vertical"],
  ["kk-dots-three-outline", "dots three outline"],
  ["kk-dots-three-outline-vertical", "dots three outline vertical"],
  ["kk-dots-three-vertical", "dots three vertical"],
  ["kk-download", "download"],
  ["kk-download-simple", "download simple"],
  ["kk-dress", "dress"],
  ["kk-dresser", "dresser"],
  ["kk-dribbble-logo", "dribbble logo"],
  ["kk-drone", "drone"],
  ["kk-drop", "drop"],
  ["kk-drop-half", "drop half"],
  ["kk-drop-half-bottom", "drop half bottom"],
  ["kk-drop-simple", "drop simple"],
  ["kk-drop-slash", "drop slash"],
  ["kk-dropbox-logo", "dropbox logo"],
  ["kk-ear", "ear"],
  ["kk-ear-slash", "ear slash"],
  ["kk-egg", "egg"],
  ["kk-egg-crack", "egg crack"],
  ["kk-eject", "eject"],
  ["kk-eject-simple", "eject simple"],
  ["kk-elevator", "elevator"],
  ["kk-empty", "empty"],
  ["kk-engine", "engine"],
  ["kk-envelope", "envelope"],
  ["kk-envelope-open", "envelope open"],
  ["kk-envelope-simple", "envelope simple"],
  ["kk-envelope-simple-open", "envelope simple open"],
  ["kk-equalizer", "equalizer"],
  ["kk-equals", "equals"],
  ["kk-eraser", "eraser"],
  ["kk-escalator-down", "escalator down"],
  ["kk-escalator-up", "escalator up"],
  ["kk-exam", "exam"],
  ["kk-exclamation-mark", "exclamation mark"],
  ["kk-exclude", "exclude"],
  ["kk-exclude-square", "exclude square"],
  ["kk-export", "export"],
  ["kk-eye", "eye"],
  ["kk-eye-closed", "eye closed"],
  ["kk-eye-slash", "eye slash"],
  ["kk-eyedropper", "eyedropper"],
  ["kk-eyedropper-sample", "eyedropper sample"],
  ["kk-eyeglasses", "eyeglasses"],
  ["kk-eyes", "eyes"],
  ["kk-face-mask", "face mask"],
  ["kk-facebook-logo", "facebook logo"],
  ["kk-factory", "factory"],
  ["kk-faders", "faders"],
  ["kk-faders-horizontal", "faders horizontal"],
  ["kk-fallout-shelter", "fallout shelter"],
  ["kk-fan", "fan"],
  ["kk-farm", "farm"],
  ["kk-fast-forward", "fast forward"],
  ["kk-fast-forward-circle", "fast forward circle"],
  ["kk-feather", "feather"],
  ["kk-fediverse-logo", "fediverse logo"],
  ["kk-figma-logo", "figma logo"],
  ["kk-file", "file"],
  ["kk-file-archive", "file archive"],
  ["kk-file-arrow-down", "file arrow down"],
  ["kk-file-arrow-up", "file arrow up"],
  ["kk-file-audio", "file audio"],
  ["kk-file-c", "file c"],
  ["kk-file-c-sharp", "file c sharp"],
  ["kk-file-cloud", "file cloud"],
  ["kk-file-code", "file code"],
  ["kk-file-cpp", "file cpp"],
  ["kk-file-css", "file css"],
  ["kk-file-csv", "file csv"],
  ["kk-file-dashed", "file dashed"],
  ["kk-file-doc", "file doc"],
  ["kk-file-html", "file html"],
  ["kk-file-image", "file image"],
  ["kk-file-ini", "file ini"],
  ["kk-file-jpg", "file jpg"],
  ["kk-file-js", "file js"],
  ["kk-file-jsx", "file jsx"],
  ["kk-file-lock", "file lock"],
  ["kk-file-magnifying-glass", "file magnifying glass"],
  ["kk-file-md", "file md"],
  ["kk-file-minus", "file minus"],
  ["kk-file-pdf", "file pdf"],
  ["kk-file-plus", "file plus"],
  ["kk-file-png", "file png"],
  ["kk-file-ppt", "file ppt"],
  ["kk-file-py", "file py"],
  ["kk-file-rs", "file rs"],
  ["kk-file-sql", "file sql"],
  ["kk-file-svg", "file svg"],
  ["kk-file-text", "file text"],
  ["kk-file-ts", "file ts"],
  ["kk-file-tsx", "file tsx"],
  ["kk-file-txt", "file txt"],
  ["kk-file-video", "file video"],
  ["kk-file-vue", "file vue"],
  ["kk-file-x", "file x"],
  ["kk-file-xls", "file xls"],
  ["kk-file-zip", "file zip"],
  ["kk-files", "files"],
  ["kk-film-reel", "film reel"],
  ["kk-film-script", "film script"],
  ["kk-film-slate", "film slate"],
  ["kk-film-strip", "film strip"],
  ["kk-fingerprint", "fingerprint"],
  ["kk-fingerprint-simple", "fingerprint simple"],
  ["kk-finn-the-human", "finn the human"],
  ["kk-fire", "fire"],
  ["kk-fire-extinguisher", "fire extinguisher"],
  ["kk-fire-simple", "fire simple"],
  ["kk-fire-truck", "fire truck"],
  ["kk-first-aid", "first aid"],
  ["kk-first-aid-kit", "first aid kit"],
  ["kk-fish", "fish"],
  ["kk-fish-simple", "fish simple"],
  ["kk-flag", "flag"],
  ["kk-flag-banner", "flag banner"],
  ["kk-flag-banner-fold", "flag banner fold"],
  ["kk-flag-checkered", "flag checkered"],
  ["kk-flag-pennant", "flag pennant"],
  ["kk-flame", "flame"],
  ["kk-flashlight", "flashlight"],
  ["kk-flask", "flask"],
  ["kk-flip-horizontal", "flip horizontal"],
  ["kk-flip-vertical", "flip vertical"],
  ["kk-floppy-disk", "floppy disk"],
  ["kk-floppy-disk-back", "floppy disk back"],
  ["kk-flow-arrow", "flow arrow"],
  ["kk-flower", "flower"],
  ["kk-flower-lotus", "flower lotus"],
  ["kk-flower-tulip", "flower tulip"],
  ["kk-flying-saucer", "flying saucer"],
  ["kk-folder", "folder"],
  ["kk-folder-dashed", "folder dashed"],
  ["kk-folder-lock", "folder lock"],
  ["kk-folder-minus", "folder minus"],
  ["kk-folder-open", "folder open"],
  ["kk-folder-plus", "folder plus"],
  ["kk-folder-simple", "folder simple"],
  ["kk-folder-simple-dashed", "folder simple dashed"],
  ["kk-folder-simple-lock", "folder simple lock"],
  ["kk-folder-simple-minus", "folder simple minus"],
  ["kk-folder-simple-plus", "folder simple plus"],
  ["kk-folder-simple-star", "folder simple star"],
  ["kk-folder-simple-user", "folder simple user"],
  ["kk-folder-star", "folder star"],
  ["kk-folder-user", "folder user"],
  ["kk-folders", "folders"],
  ["kk-football", "football"],
  ["kk-football-helmet", "football helmet"],
  ["kk-footprints", "footprints"],
  ["kk-fork-knife", "fork knife"],
  ["kk-four-k", "four k"],
  ["kk-frame-corners", "frame corners"],
  ["kk-framer-logo", "framer logo"],
  ["kk-function", "function"],
  ["kk-funnel", "funnel"],
  ["kk-funnel-simple", "funnel simple"],
  ["kk-funnel-simple-x", "funnel simple x"],
  ["kk-funnel-x", "funnel x"],
  ["kk-game-controller", "game controller"],
  ["kk-garage", "garage"],
  ["kk-gas-can", "gas can"],
  ["kk-gas-pump", "gas pump"],
  ["kk-gauge", "gauge"],
  ["kk-gavel", "gavel"],
  ["kk-gear", "gear"],
  ["kk-gear-fine", "gear fine"],
  ["kk-gear-six", "gear six"],
  ["kk-gender-female", "gender female"],
  ["kk-gender-intersex", "gender intersex"],
  ["kk-gender-male", "gender male"],
  ["kk-gender-neuter", "gender neuter"],
  ["kk-gender-nonbinary", "gender nonbinary"],
  ["kk-gender-transgender", "gender transgender"],
  ["kk-ghost", "ghost"],
  ["kk-gif", "gif"],
  ["kk-gift", "gift"],
  ["kk-git-branch", "git branch"],
  ["kk-git-commit", "git commit"],
  ["kk-git-diff", "git diff"],
  ["kk-git-fork", "git fork"],
  ["kk-git-merge", "git merge"],
  ["kk-git-pull-request", "git pull request"],
  ["kk-github-logo", "github logo"],
  ["kk-gitlab-logo", "gitlab logo"],
  ["kk-gitlab-logo-simple", "gitlab logo simple"],
  ["kk-globe", "globe"],
  ["kk-globe-hemisphere-east", "globe hemisphere east"],
  ["kk-globe-hemisphere-west", "globe hemisphere west"],
  ["kk-globe-simple", "globe simple"],
  ["kk-globe-simple-x", "globe simple x"],
  ["kk-globe-stand", "globe stand"],
  ["kk-globe-x", "globe x"],
  ["kk-goggles", "goggles"],
  ["kk-golf", "golf"],
  ["kk-goodreads-logo", "goodreads logo"],
  ["kk-google-cardboard-logo", "google cardboard logo"],
  ["kk-google-chrome-logo", "google chrome logo"],
  ["kk-google-drive-logo", "google drive logo"],
  ["kk-google-logo", "google logo"],
  ["kk-google-photos-logo", "google photos logo"],
  ["kk-google-play-logo", "google play logo"],
  ["kk-google-podcasts-logo", "google podcasts logo"],
  ["kk-gps", "gps"],
  ["kk-gps-fix", "gps fix"],
  ["kk-gps-slash", "gps slash"],
  ["kk-gradient", "gradient"],
  ["kk-graduation-cap", "graduation cap"],
  ["kk-grains", "grains"],
  ["kk-grains-slash", "grains slash"],
  ["kk-graph", "graph"],
  ["kk-graphics-card", "graphics card"],
  ["kk-greater-than", "greater than"],
  ["kk-greater-than-or-equal", "greater than or equal"],
  ["kk-grid-four", "grid four"],
  ["kk-grid-nine", "grid nine"],
  ["kk-guitar", "guitar"],
  ["kk-hair-dryer", "hair dryer"],
  ["kk-hamburger", "hamburger"],
  ["kk-hammer", "hammer"],
  ["kk-hand", "hand"],
  ["kk-hand-arrow-down", "hand arrow down"],
  ["kk-hand-arrow-up", "hand arrow up"],
  ["kk-hand-coins", "hand coins"],
  ["kk-hand-deposit", "hand deposit"],
  ["kk-hand-eye", "hand eye"],
  ["kk-hand-fist", "hand fist"],
  ["kk-hand-grabbing", "hand grabbing"],
  ["kk-hand-heart", "hand heart"],
  ["kk-hand-palm", "hand palm"],
  ["kk-hand-peace", "hand peace"],
  ["kk-hand-pointing", "hand pointing"],
  ["kk-hand-soap", "hand soap"],
  ["kk-hand-swipe-left", "hand swipe left"],
  ["kk-hand-swipe-right", "hand swipe right"],
  ["kk-hand-tap", "hand tap"],
  ["kk-hand-waving", "hand waving"],
  ["kk-hand-withdraw", "hand withdraw"],
  ["kk-handbag", "handbag"],
  ["kk-handbag-simple", "handbag simple"],
  ["kk-hands-clapping", "hands clapping"],
  ["kk-hands-praying", "hands praying"],
  ["kk-handshake", "handshake"],
  ["kk-hard-drive", "hard drive"],
  ["kk-hard-drives", "hard drives"],
  ["kk-hard-hat", "hard hat"],
  ["kk-hash", "hash"],
  ["kk-hash-straight", "hash straight"],
  ["kk-head-circuit", "head circuit"],
  ["kk-headlights", "headlights"],
  ["kk-headphones", "headphones"],
  ["kk-headset", "headset"],
  ["kk-heart", "heart"],
  ["kk-heart-break", "heart break"],
  ["kk-heart-half", "heart half"],
  ["kk-heart-straight", "heart straight"],
  ["kk-heart-straight-break", "heart straight break"],
  ["kk-heartbeat", "heartbeat"],
  ["kk-hexagon", "hexagon"],
  ["kk-high-definition", "high definition"],
  ["kk-high-heel", "high heel"],
  ["kk-highlighter", "highlighter"],
  ["kk-highlighter-circle", "highlighter circle"],
  ["kk-hockey", "hockey"],
  ["kk-hoodie", "hoodie"],
  ["kk-horse", "horse"],
  ["kk-hospital", "hospital"],
  ["kk-hourglass", "hourglass"],
  ["kk-hourglass-high", "hourglass high"],
  ["kk-hourglass-low", "hourglass low"],
  ["kk-hourglass-medium", "hourglass medium"],
  ["kk-hourglass-simple", "hourglass simple"],
  ["kk-hourglass-simple-high", "hourglass simple high"],
  ["kk-hourglass-simple-low", "hourglass simple low"],
  ["kk-hourglass-simple-medium", "hourglass simple medium"],
  ["kk-house", "house"],
  ["kk-house-line", "house line"],
  ["kk-house-simple", "house simple"],
  ["kk-hurricane", "hurricane"],
  ["kk-ice-cream", "ice cream"],
  ["kk-identification-badge", "identification badge"],
  ["kk-identification-card", "identification card"],
  ["kk-image", "image"],
  ["kk-image-broken", "image broken"],
  ["kk-image-square", "image square"],
  ["kk-images", "images"],
  ["kk-images-square", "images square"],
  ["kk-infinity", "infinity"],
  ["kk-info", "info"],
  ["kk-instagram-logo", "instagram logo"],
  ["kk-intersect", "intersect"],
  ["kk-intersect-square", "intersect square"],
  ["kk-intersect-three", "intersect three"],
  ["kk-intersection", "intersection"],
  ["kk-invoice", "invoice"],
  ["kk-island", "island"],
  ["kk-jar", "jar"],
  ["kk-jar-label", "jar label"],
  ["kk-jeep", "jeep"],
  ["kk-joystick", "joystick"],
  ["kk-kanban", "kanban"],
  ["kk-key", "key"],
  ["kk-key-return", "key return"],
  ["kk-keyboard", "keyboard"],
  ["kk-keyhole", "keyhole"],
  ["kk-knife", "knife"],
  ["kk-ladder", "ladder"],
  ["kk-ladder-simple", "ladder simple"],
  ["kk-lamp", "lamp"],
  ["kk-lamp-pendant", "lamp pendant"],
  ["kk-laptop", "laptop"],
  ["kk-lasso", "lasso"],
  ["kk-lastfm-logo", "lastfm logo"],
  ["kk-layout", "layout"],
  ["kk-leaf", "leaf"],
  ["kk-lectern", "lectern"],
  ["kk-lego", "lego"],
  ["kk-lego-smiley", "lego smiley"],
  ["kk-less-than", "less than"],
  ["kk-less-than-or-equal", "less than or equal"],
  ["kk-letter-circle-h", "letter circle h"],
  ["kk-letter-circle-p", "letter circle p"],
  ["kk-letter-circle-v", "letter circle v"],
  ["kk-lifebuoy", "lifebuoy"],
  ["kk-lightbulb", "lightbulb"],
  ["kk-lightbulb-filament", "lightbulb filament"],
  ["kk-lighthouse", "lighthouse"],
  ["kk-lightning", "lightning"],
  ["kk-lightning-a", "lightning a"],
  ["kk-lightning-slash", "lightning slash"],
  ["kk-line-segment", "line segment"],
  ["kk-line-segments", "line segments"],
  ["kk-line-vertical", "line vertical"],
  ["kk-link", "link"],
  ["kk-link-break", "link break"],
  ["kk-link-simple", "link simple"],
  ["kk-link-simple-break", "link simple break"],
  ["kk-link-simple-horizontal", "link simple horizontal"],
  ["kk-link-simple-horizontal-break", "link simple horizontal break"],
  ["kk-linkedin-logo", "linkedin logo"],
  ["kk-linktree-logo", "linktree logo"],
  ["kk-linux-logo", "linux logo"],
  ["kk-list", "list"],
  ["kk-list-bullets", "list bullets"],
  ["kk-list-checks", "list checks"],
  ["kk-list-dashes", "list dashes"],
  ["kk-list-heart", "list heart"],
  ["kk-list-magnifying-glass", "list magnifying glass"],
  ["kk-list-numbers", "list numbers"],
  ["kk-list-plus", "list plus"],
  ["kk-list-star", "list star"],
  ["kk-lock", "lock"],
  ["kk-lock-key", "lock key"],
  ["kk-lock-key-open", "lock key open"],
  ["kk-lock-laminated", "lock laminated"],
  ["kk-lock-laminated-open", "lock laminated open"],
  ["kk-lock-open", "lock open"],
  ["kk-lock-simple", "lock simple"],
  ["kk-lock-simple-open", "lock simple open"],
  ["kk-lockers", "lockers"],
  ["kk-log", "log"],
  ["kk-magic-wand", "magic wand"],
  ["kk-magnet", "magnet"],
  ["kk-magnet-straight", "magnet straight"],
  ["kk-magnifying-glass", "magnifying glass"],
  ["kk-magnifying-glass-minus", "magnifying glass minus"],
  ["kk-magnifying-glass-plus", "magnifying glass plus"],
  ["kk-mailbox", "mailbox"],
  ["kk-map-pin", "map pin"],
  ["kk-map-pin-area", "map pin area"],
  ["kk-map-pin-line", "map pin line"],
  ["kk-map-pin-plus", "map pin plus"],
  ["kk-map-pin-simple", "map pin simple"],
  ["kk-map-pin-simple-area", "map pin simple area"],
  ["kk-map-pin-simple-line", "map pin simple line"],
  ["kk-map-trifold", "map trifold"],
  ["kk-markdown-logo", "markdown logo"],
  ["kk-marker-circle", "marker circle"],
  ["kk-martini", "martini"],
  ["kk-mask-happy", "mask happy"],
  ["kk-mask-sad", "mask sad"],
  ["kk-mastodon-logo", "mastodon logo"],
  ["kk-math-operations", "math operations"],
  ["kk-matrix-logo", "matrix logo"],
  ["kk-medal", "medal"],
  ["kk-medal-military", "medal military"],
  ["kk-medium-logo", "medium logo"],
  ["kk-megaphone", "megaphone"],
  ["kk-megaphone-simple", "megaphone simple"],
  ["kk-member-of", "member of"],
  ["kk-memory", "memory"],
  ["kk-messenger-logo", "messenger logo"],
  ["kk-meta-logo", "meta logo"],
  ["kk-meteor", "meteor"],
  ["kk-metronome", "metronome"],
  ["kk-microphone", "microphone"],
  ["kk-microphone-slash", "microphone slash"],
  ["kk-microphone-stage", "microphone stage"],
  ["kk-microscope", "microscope"],
  ["kk-microsoft-excel-logo", "microsoft excel logo"],
  ["kk-microsoft-outlook-logo", "microsoft outlook logo"],
  ["kk-microsoft-powerpoint-logo", "microsoft powerpoint logo"],
  ["kk-microsoft-teams-logo", "microsoft teams logo"],
  ["kk-microsoft-word-logo", "microsoft word logo"],
  ["kk-minus", "minus"],
  ["kk-minus-circle", "minus circle"],
  ["kk-minus-square", "minus square"],
  ["kk-money", "money"],
  ["kk-money-wavy", "money wavy"],
  ["kk-monitor", "monitor"],
  ["kk-monitor-arrow-up", "monitor arrow up"],
  ["kk-monitor-play", "monitor play"],
  ["kk-moon", "moon"],
  ["kk-moon-stars", "moon stars"],
  ["kk-moped", "moped"],
  ["kk-moped-front", "moped front"],
  ["kk-mosque", "mosque"],
  ["kk-motorcycle", "motorcycle"],
  ["kk-mountains", "mountains"],
  ["kk-mouse", "mouse"],
  ["kk-mouse-left-click", "mouse left click"],
  ["kk-mouse-middle-click", "mouse middle click"],
  ["kk-mouse-right-click", "mouse right click"],
  ["kk-mouse-scroll", "mouse scroll"],
  ["kk-mouse-simple", "mouse simple"],
  ["kk-music-note", "music note"],
  ["kk-music-note-simple", "music note simple"],
  ["kk-music-notes", "music notes"],
  ["kk-music-notes-minus", "music notes minus"],
  ["kk-music-notes-plus", "music notes plus"],
  ["kk-music-notes-simple", "music notes simple"],
  ["kk-navigation-arrow", "navigation arrow"],
  ["kk-needle", "needle"],
  ["kk-network", "network"],
  ["kk-network-slash", "network slash"],
  ["kk-network-x", "network x"],
  ["kk-newspaper", "newspaper"],
  ["kk-newspaper-clipping", "newspaper clipping"],
  ["kk-not-equals", "not equals"],
  ["kk-not-member-of", "not member of"],
  ["kk-not-subset-of", "not subset of"],
  ["kk-not-superset-of", "not superset of"],
  ["kk-notches", "notches"],
  ["kk-note", "note"],
  ["kk-note-blank", "note blank"],
  ["kk-note-pencil", "note pencil"],
  ["kk-notebook", "notebook"],
  ["kk-notepad", "notepad"],
  ["kk-notification", "notification"],
  ["kk-notion-logo", "notion logo"],
  ["kk-nuclear-plant", "nuclear plant"],
  ["kk-number-circle-eight", "number circle eight"],
  ["kk-number-circle-five", "number circle five"],
  ["kk-number-circle-four", "number circle four"],
  ["kk-number-circle-nine", "number circle nine"],
  ["kk-number-circle-one", "number circle one"],
  ["kk-number-circle-seven", "number circle seven"],
  ["kk-number-circle-six", "number circle six"],
  ["kk-number-circle-three", "number circle three"],
  ["kk-number-circle-two", "number circle two"],
  ["kk-number-circle-zero", "number circle zero"],
  ["kk-number-eight", "number eight"],
  ["kk-number-five", "number five"],
  ["kk-number-four", "number four"],
  ["kk-number-nine", "number nine"],
  ["kk-number-one", "number one"],
  ["kk-number-seven", "number seven"],
  ["kk-number-six", "number six"],
  ["kk-number-square-eight", "number square eight"],
  ["kk-number-square-five", "number square five"],
  ["kk-number-square-four", "number square four"],
  ["kk-number-square-nine", "number square nine"],
  ["kk-number-square-one", "number square one"],
  ["kk-number-square-seven", "number square seven"],
  ["kk-number-square-six", "number square six"],
  ["kk-number-square-three", "number square three"],
  ["kk-number-square-two", "number square two"],
  ["kk-number-square-zero", "number square zero"],
  ["kk-number-three", "number three"],
  ["kk-number-two", "number two"],
  ["kk-number-zero", "number zero"],
  ["kk-numpad", "numpad"],
  ["kk-nut", "nut"],
  ["kk-ny-times-logo", "ny times logo"],
  ["kk-octagon", "octagon"],
  ["kk-office-chair", "office chair"],
  ["kk-onigiri", "onigiri"],
  ["kk-open-ai-logo", "open ai logo"],
  ["kk-option", "option"],
  ["kk-orange", "orange"],
  ["kk-orange-slice", "orange slice"],
  ["kk-oven", "oven"],
  ["kk-package", "package"],
  ["kk-paint-brush", "paint brush"],
  ["kk-paint-brush-broad", "paint brush broad"],
  ["kk-paint-brush-household", "paint brush household"],
  ["kk-paint-bucket", "paint bucket"],
  ["kk-paint-roller", "paint roller"],
  ["kk-palette", "palette"],
  ["kk-panorama", "panorama"],
  ["kk-pants", "pants"],
  ["kk-paper-plane", "paper plane"],
  ["kk-paper-plane-right", "paper plane right"],
  ["kk-paper-plane-tilt", "paper plane tilt"],
  ["kk-paperclip", "paperclip"],
  ["kk-paperclip-horizontal", "paperclip horizontal"],
  ["kk-parachute", "parachute"],
  ["kk-paragraph", "paragraph"],
  ["kk-parallelogram", "parallelogram"],
  ["kk-park", "park"],
  ["kk-password", "password"],
  ["kk-path", "path"],
  ["kk-patreon-logo", "patreon logo"],
  ["kk-pause", "pause"],
  ["kk-pause-circle", "pause circle"],
  ["kk-paw-print", "paw print"],
  ["kk-paypal-logo", "paypal logo"],
  ["kk-peace", "peace"],
  ["kk-pen", "pen"],
  ["kk-pen-nib", "pen nib"],
  ["kk-pen-nib-straight", "pen nib straight"],
  ["kk-pencil", "pencil"],
  ["kk-pencil-circle", "pencil circle"],
  ["kk-pencil-line", "pencil line"],
  ["kk-pencil-ruler", "pencil ruler"],
  ["kk-pencil-simple", "pencil simple"],
  ["kk-pencil-simple-line", "pencil simple line"],
  ["kk-pencil-simple-slash", "pencil simple slash"],
  ["kk-pencil-slash", "pencil slash"],
  ["kk-pentagon", "pentagon"],
  ["kk-pentagram", "pentagram"],
  ["kk-pepper", "pepper"],
  ["kk-percent", "percent"],
  ["kk-person", "person"],
  ["kk-person-arms-spread", "person arms spread"],
  ["kk-person-simple", "person simple"],
  ["kk-person-simple-bike", "person simple bike"],
  ["kk-person-simple-circle", "person simple circle"],
  ["kk-person-simple-hike", "person simple hike"],
  ["kk-person-simple-run", "person simple run"],
  ["kk-person-simple-ski", "person simple ski"],
  ["kk-person-simple-snowboard", "person simple snowboard"],
  ["kk-person-simple-swim", "person simple swim"],
  ["kk-person-simple-tai-chi", "person simple tai chi"],
  ["kk-person-simple-throw", "person simple throw"],
  ["kk-person-simple-walk", "person simple walk"],
  ["kk-perspective", "perspective"],
  ["kk-phone", "phone"],
  ["kk-phone-call", "phone call"],
  ["kk-phone-disconnect", "phone disconnect"],
  ["kk-phone-incoming", "phone incoming"],
  ["kk-phone-list", "phone list"],
  ["kk-phone-outgoing", "phone outgoing"],
  ["kk-phone-pause", "phone pause"],
  ["kk-phone-plus", "phone plus"],
  ["kk-phone-slash", "phone slash"],
  ["kk-phone-transfer", "phone transfer"],
  ["kk-phone-x", "phone x"],
  ["kk-phosphor-logo", "phosphor logo"],
  ["kk-pi", "pi"],
  ["kk-piano-keys", "piano keys"],
  ["kk-picnic-table", "picnic table"],
  ["kk-picture-in-picture", "picture in picture"],
  ["kk-piggy-bank", "piggy bank"],
  ["kk-pill", "pill"],
  ["kk-ping-pong", "ping pong"],
  ["kk-pint-glass", "pint glass"],
  ["kk-pinterest-logo", "pinterest logo"],
  ["kk-pinwheel", "pinwheel"],
  ["kk-pipe", "pipe"],
  ["kk-pipe-wrench", "pipe wrench"],
  ["kk-pix-logo", "pix logo"],
  ["kk-pizza", "pizza"],
  ["kk-placeholder", "placeholder"],
  ["kk-planet", "planet"],
  ["kk-plant", "plant"],
  ["kk-play", "play"],
  ["kk-play-circle", "play circle"],
  ["kk-play-pause", "play pause"],
  ["kk-playlist", "playlist"],
  ["kk-plug", "plug"],
  ["kk-plug-charging", "plug charging"],
  ["kk-plugs", "plugs"],
  ["kk-plugs-connected", "plugs connected"],
  ["kk-plus", "plus"],
  ["kk-plus-circle", "plus circle"],
  ["kk-plus-minus", "plus minus"],
  ["kk-plus-square", "plus square"],
  ["kk-poker-chip", "poker chip"],
  ["kk-police-car", "police car"],
  ["kk-polygon", "polygon"],
  ["kk-popcorn", "popcorn"],
  ["kk-popsicle", "popsicle"],
  ["kk-potted-plant", "potted plant"],
  ["kk-power", "power"],
  ["kk-prescription", "prescription"],
  ["kk-presentation", "presentation"],
  ["kk-presentation-chart", "presentation chart"],
  ["kk-printer", "printer"],
  ["kk-prohibit", "prohibit"],
  ["kk-prohibit-inset", "prohibit inset"],
  ["kk-projector-screen", "projector screen"],
  ["kk-projector-screen-chart", "projector screen chart"],
  ["kk-pulse", "pulse"],
  ["kk-push-pin", "push pin"],
  ["kk-push-pin-simple", "push pin simple"],
  ["kk-push-pin-simple-slash", "push pin simple slash"],
  ["kk-push-pin-slash", "push pin slash"],
  ["kk-puzzle-piece", "puzzle piece"],
  ["kk-qr-code", "qr code"],
  ["kk-question", "question"],
  ["kk-question-mark", "question mark"],
  ["kk-queue", "queue"],
  ["kk-quotes", "quotes"],
  ["kk-rabbit", "rabbit"],
  ["kk-racquet", "racquet"],
  ["kk-radical", "radical"],
  ["kk-radio", "radio"],
  ["kk-radio-button", "radio button"],
  ["kk-radioactive", "radioactive"],
  ["kk-rainbow", "rainbow"],
  ["kk-rainbow-cloud", "rainbow cloud"],
  ["kk-ranking", "ranking"],
  ["kk-read-cv-logo", "read cv logo"],
  ["kk-receipt", "receipt"],
  ["kk-receipt-x", "receipt x"],
  ["kk-record", "record"],
  ["kk-rectangle", "rectangle"],
  ["kk-rectangle-dashed", "rectangle dashed"],
  ["kk-recycle", "recycle"],
  ["kk-reddit-logo", "reddit logo"],
  ["kk-repeat", "repeat"],
  ["kk-repeat-once", "repeat once"],
  ["kk-replit-logo", "replit logo"],
  ["kk-resize", "resize"],
  ["kk-rewind", "rewind"],
  ["kk-rewind-circle", "rewind circle"],
  ["kk-road-horizon", "road horizon"],
  ["kk-robot", "robot"],
  ["kk-rocket", "rocket"],
  ["kk-rocket-launch", "rocket launch"],
  ["kk-rows", "rows"],
  ["kk-rows-plus-bottom", "rows plus bottom"],
  ["kk-rows-plus-top", "rows plus top"],
  ["kk-rss", "rss"],
  ["kk-rss-simple", "rss simple"],
  ["kk-rug", "rug"],
  ["kk-ruler", "ruler"],
  ["kk-sailboat", "sailboat"],
  ["kk-scales", "scales"],
  ["kk-scan", "scan"],
  ["kk-scan-smiley", "scan smiley"],
  ["kk-scissors", "scissors"],
  ["kk-scooter", "scooter"],
  ["kk-screencast", "screencast"],
  ["kk-screwdriver", "screwdriver"],
  ["kk-scribble", "scribble"],
  ["kk-scribble-loop", "scribble loop"],
  ["kk-scroll", "scroll"],
  ["kk-seal", "seal"],
  ["kk-seal-check", "seal check"],
  ["kk-seal-percent", "seal percent"],
  ["kk-seal-question", "seal question"],
  ["kk-seal-warning", "seal warning"],
  ["kk-seat", "seat"],
  ["kk-seatbelt", "seatbelt"],
  ["kk-security-camera", "security camera"],
  ["kk-selection", "selection"],
  ["kk-selection-all", "selection all"],
  ["kk-selection-background", "selection background"],
  ["kk-selection-foreground", "selection foreground"],
  ["kk-selection-inverse", "selection inverse"],
  ["kk-selection-plus", "selection plus"],
  ["kk-selection-slash", "selection slash"],
  ["kk-shapes", "shapes"],
  ["kk-share", "share"],
  ["kk-share-fat", "share fat"],
  ["kk-share-network", "share network"],
  ["kk-shield", "shield"],
  ["kk-shield-check", "shield check"],
  ["kk-shield-checkered", "shield checkered"],
  ["kk-shield-chevron", "shield chevron"],
  ["kk-shield-plus", "shield plus"],
  ["kk-shield-slash", "shield slash"],
  ["kk-shield-star", "shield star"],
  ["kk-shield-warning", "shield warning"],
  ["kk-shipping-container", "shipping container"],
  ["kk-shirt-folded", "shirt folded"],
  ["kk-shooting-star", "shooting star"],
  ["kk-shopping-bag", "shopping bag"],
  ["kk-shopping-bag-open", "shopping bag open"],
  ["kk-shopping-cart", "shopping cart"],
  ["kk-shopping-cart-simple", "shopping cart simple"],
  ["kk-shovel", "shovel"],
  ["kk-shower", "shower"],
  ["kk-shrimp", "shrimp"],
  ["kk-shuffle", "shuffle"],
  ["kk-shuffle-angular", "shuffle angular"],
  ["kk-shuffle-simple", "shuffle simple"],
  ["kk-sidebar", "sidebar"],
  ["kk-sidebar-simple", "sidebar simple"],
  ["kk-sigma", "sigma"],
  ["kk-sign-in", "sign in"],
  ["kk-sign-out", "sign out"],
  ["kk-signature", "signature"],
  ["kk-signpost", "signpost"],
  ["kk-sim-card", "sim card"],
  ["kk-siren", "siren"],
  ["kk-sketch-logo", "sketch logo"],
  ["kk-skip-back", "skip back"],
  ["kk-skip-back-circle", "skip back circle"],
  ["kk-skip-forward", "skip forward"],
  ["kk-skip-forward-circle", "skip forward circle"],
  ["kk-skull", "skull"],
  ["kk-skype-logo", "skype logo"],
  ["kk-slack-logo", "slack logo"],
  ["kk-sliders", "sliders"],
  ["kk-sliders-horizontal", "sliders horizontal"],
  ["kk-slideshow", "slideshow"],
  ["kk-smiley", "smiley"],
  ["kk-smiley-angry", "smiley angry"],
  ["kk-smiley-blank", "smiley blank"],
  ["kk-smiley-meh", "smiley meh"],
  ["kk-smiley-melting", "smiley melting"],
  ["kk-smiley-nervous", "smiley nervous"],
  ["kk-smiley-sad", "smiley sad"],
  ["kk-smiley-sticker", "smiley sticker"],
  ["kk-smiley-wink", "smiley wink"],
  ["kk-smiley-x-eyes", "smiley x eyes"],
  ["kk-snapchat-logo", "snapchat logo"],
  ["kk-sneaker", "sneaker"],
  ["kk-sneaker-move", "sneaker move"],
  ["kk-snowflake", "snowflake"],
  ["kk-soccer-ball", "soccer ball"],
  ["kk-sock", "sock"],
  ["kk-solar-panel", "solar panel"],
  ["kk-solar-roof", "solar roof"],
  ["kk-sort-ascending", "sort ascending"],
  ["kk-sort-descending", "sort descending"],
  ["kk-soundcloud-logo", "soundcloud logo"],
  ["kk-spade", "spade"],
  ["kk-sparkle", "sparkle"],
  ["kk-speaker-hifi", "speaker hifi"],
  ["kk-speaker-high", "speaker high"],
  ["kk-speaker-low", "speaker low"],
  ["kk-speaker-none", "speaker none"],
  ["kk-speaker-simple-high", "speaker simple high"],
  ["kk-speaker-simple-low", "speaker simple low"],
  ["kk-speaker-simple-none", "speaker simple none"],
  ["kk-speaker-simple-slash", "speaker simple slash"],
  ["kk-speaker-simple-x", "speaker simple x"],
  ["kk-speaker-slash", "speaker slash"],
  ["kk-speaker-x", "speaker x"],
  ["kk-speedometer", "speedometer"],
  ["kk-sphere", "sphere"],
  ["kk-spinner", "spinner"],
  ["kk-spinner-ball", "spinner ball"],
  ["kk-spinner-gap", "spinner gap"],
  ["kk-spiral", "spiral"],
  ["kk-split-horizontal", "split horizontal"],
  ["kk-split-vertical", "split vertical"],
  ["kk-spotify-logo", "spotify logo"],
  ["kk-spray-bottle", "spray bottle"],
  ["kk-square", "square"],
  ["kk-square-half", "square half"],
  ["kk-square-half-bottom", "square half bottom"],
  ["kk-square-logo", "square logo"],
  ["kk-square-split-horizontal", "square split horizontal"],
  ["kk-square-split-vertical", "square split vertical"],
  ["kk-squares-four", "squares four"],
  ["kk-stack", "stack"],
  ["kk-stack-minus", "stack minus"],
  ["kk-stack-overflow-logo", "stack overflow logo"],
  ["kk-stack-plus", "stack plus"],
  ["kk-stack-simple", "stack simple"],
  ["kk-stairs", "stairs"],
  ["kk-stamp", "stamp"],
  ["kk-standard-definition", "standard definition"],
  ["kk-star", "star"],
  ["kk-star-and-crescent", "star and crescent"],
  ["kk-star-four", "star four"],
  ["kk-star-half", "star half"],
  ["kk-star-of-david", "star of david"],
  ["kk-steam-logo", "steam logo"],
  ["kk-steering-wheel", "steering wheel"],
  ["kk-steps", "steps"],
  ["kk-stethoscope", "stethoscope"],
  ["kk-sticker", "sticker"],
  ["kk-stool", "stool"],
  ["kk-stop", "stop"],
  ["kk-stop-circle", "stop circle"],
  ["kk-storefront", "storefront"],
  ["kk-strategy", "strategy"],
  ["kk-stripe-logo", "stripe logo"],
  ["kk-student", "student"],
  ["kk-subset-of", "subset of"],
  ["kk-subset-proper-of", "subset proper of"],
  ["kk-subtitles", "subtitles"],
  ["kk-subtitles-slash", "subtitles slash"],
  ["kk-subtract", "subtract"],
  ["kk-subtract-square", "subtract square"],
  ["kk-subway", "subway"],
  ["kk-suitcase", "suitcase"],
  ["kk-suitcase-rolling", "suitcase rolling"],
  ["kk-suitcase-simple", "suitcase simple"],
  ["kk-sun", "sun"],
  ["kk-sun-dim", "sun dim"],
  ["kk-sun-horizon", "sun horizon"],
  ["kk-sunglasses", "sunglasses"],
  ["kk-superset-of", "superset of"],
  ["kk-superset-proper-of", "superset proper of"],
  ["kk-swap", "swap"],
  ["kk-swatches", "swatches"],
  ["kk-swimming-pool", "swimming pool"],
  ["kk-sword", "sword"],
  ["kk-synagogue", "synagogue"],
  ["kk-syringe", "syringe"],
  ["kk-t-shirt", "t shirt"],
  ["kk-table", "table"],
  ["kk-tabs", "tabs"],
  ["kk-tag", "tag"],
  ["kk-tag-chevron", "tag chevron"],
  ["kk-tag-simple", "tag simple"],
  ["kk-target", "target"],
  ["kk-taxi", "taxi"],
  ["kk-tea-bag", "tea bag"],
  ["kk-telegram-logo", "telegram logo"],
  ["kk-television", "television"],
  ["kk-television-simple", "television simple"],
  ["kk-tennis-ball", "tennis ball"],
  ["kk-tent", "tent"],
  ["kk-terminal", "terminal"],
  ["kk-terminal-window", "terminal window"],
  ["kk-test-tube", "test tube"],
  ["kk-text-a-underline", "text a underline"],
  ["kk-text-aa", "text aa"],
  ["kk-text-align-center", "text align center"],
  ["kk-text-align-justify", "text align justify"],
  ["kk-text-align-left", "text align left"],
  ["kk-text-align-right", "text align right"],
  ["kk-text-b", "text b"],
  ["kk-text-columns", "text columns"],
  ["kk-text-h", "text h"],
  ["kk-text-h-five", "text h five"],
  ["kk-text-h-four", "text h four"],
  ["kk-text-h-one", "text h one"],
  ["kk-text-h-six", "text h six"],
  ["kk-text-h-three", "text h three"],
  ["kk-text-h-two", "text h two"],
  ["kk-text-indent", "text indent"],
  ["kk-text-italic", "text italic"],
  ["kk-text-outdent", "text outdent"],
  ["kk-text-strikethrough", "text strikethrough"],
  ["kk-text-subscript", "text subscript"],
  ["kk-text-superscript", "text superscript"],
  ["kk-text-t", "text t"],
  ["kk-text-t-slash", "text t slash"],
  ["kk-text-underline", "text underline"],
  ["kk-textbox", "textbox"],
  ["kk-thermometer", "thermometer"],
  ["kk-thermometer-cold", "thermometer cold"],
  ["kk-thermometer-hot", "thermometer hot"],
  ["kk-thermometer-simple", "thermometer simple"],
  ["kk-threads-logo", "threads logo"],
  ["kk-three-d", "three d"],
  ["kk-thumbs-down", "thumbs down"],
  ["kk-thumbs-up", "thumbs up"],
  ["kk-ticket", "ticket"],
  ["kk-tidal-logo", "tidal logo"],
  ["kk-tiktok-logo", "tiktok logo"],
  ["kk-tilde", "tilde"],
  ["kk-timer", "timer"],
  ["kk-tip-jar", "tip jar"],
  ["kk-tipi", "tipi"],
  ["kk-tire", "tire"],
  ["kk-toggle-left", "toggle left"],
  ["kk-toggle-right", "toggle right"],
  ["kk-toilet", "toilet"],
  ["kk-toilet-paper", "toilet paper"],
  ["kk-toolbox", "toolbox"],
  ["kk-tooth", "tooth"],
  ["kk-tornado", "tornado"],
  ["kk-tote", "tote"],
  ["kk-tote-simple", "tote simple"],
  ["kk-towel", "towel"],
  ["kk-tractor", "tractor"],
  ["kk-trademark", "trademark"],
  ["kk-trademark-registered", "trademark registered"],
  ["kk-traffic-cone", "traffic cone"],
  ["kk-traffic-sign", "traffic sign"],
  ["kk-traffic-signal", "traffic signal"],
  ["kk-train", "train"],
  ["kk-train-regional", "train regional"],
  ["kk-train-simple", "train simple"],
  ["kk-tram", "tram"],
  ["kk-translate", "translate"],
  ["kk-trash", "trash"],
  ["kk-trash-simple", "trash simple"],
  ["kk-tray", "tray"],
  ["kk-tray-arrow-down", "tray arrow down"],
  ["kk-tray-arrow-up", "tray arrow up"],
  ["kk-treasure-chest", "treasure chest"],
  ["kk-tree", "tree"],
  ["kk-tree-evergreen", "tree evergreen"],
  ["kk-tree-palm", "tree palm"],
  ["kk-tree-structure", "tree structure"],
  ["kk-tree-view", "tree view"],
  ["kk-trend-down", "trend down"],
  ["kk-trend-up", "trend up"],
  ["kk-triangle", "triangle"],
  ["kk-triangle-dashed", "triangle dashed"],
  ["kk-trolley", "trolley"],
  ["kk-trolley-suitcase", "trolley suitcase"],
  ["kk-trophy", "trophy"],
  ["kk-truck", "truck"],
  ["kk-truck-trailer", "truck trailer"],
  ["kk-tumblr-logo", "tumblr logo"],
  ["kk-twitch-logo", "twitch logo"],
  ["kk-twitter-logo", "twitter logo"],
  ["kk-umbrella", "umbrella"],
  ["kk-umbrella-simple", "umbrella simple"],
  ["kk-union", "union"],
  ["kk-unite", "unite"],
  ["kk-unite-square", "unite square"],
  ["kk-upload", "upload"],
  ["kk-upload-simple", "upload simple"],
  ["kk-usb", "usb"],
  ["kk-user", "user"],
  ["kk-user-check", "user check"],
  ["kk-user-circle", "user circle"],
  ["kk-user-circle-check", "user circle check"],
  ["kk-user-circle-dashed", "user circle dashed"],
  ["kk-user-circle-gear", "user circle gear"],
  ["kk-user-circle-minus", "user circle minus"],
  ["kk-user-circle-plus", "user circle plus"],
  ["kk-user-focus", "user focus"],
  ["kk-user-gear", "user gear"],
  ["kk-user-list", "user list"],
  ["kk-user-minus", "user minus"],
  ["kk-user-plus", "user plus"],
  ["kk-user-rectangle", "user rectangle"],
  ["kk-user-sound", "user sound"],
  ["kk-user-square", "user square"],
  ["kk-user-switch", "user switch"],
  ["kk-users", "users"],
  ["kk-users-four", "users four"],
  ["kk-users-three", "users three"],
  ["kk-van", "van"],
  ["kk-vault", "vault"],
  ["kk-vector-three", "vector three"],
  ["kk-vector-two", "vector two"],
  ["kk-vibrate", "vibrate"],
  ["kk-video", "video"],
  ["kk-video-camera", "video camera"],
  ["kk-video-camera-slash", "video camera slash"],
  ["kk-video-conference", "video conference"],
  ["kk-vignette", "vignette"],
  ["kk-vinyl-record", "vinyl record"],
  ["kk-virtual-reality", "virtual reality"],
  ["kk-virus", "virus"],
  ["kk-visor", "visor"],
  ["kk-voicemail", "voicemail"],
  ["kk-volleyball", "volleyball"],
  ["kk-wall", "wall"],
  ["kk-wallet", "wallet"],
  ["kk-warehouse", "warehouse"],
  ["kk-warning", "warning"],
  ["kk-warning-circle", "warning circle"],
  ["kk-warning-diamond", "warning diamond"],
  ["kk-warning-octagon", "warning octagon"],
  ["kk-washing-machine", "washing machine"],
  ["kk-watch", "watch"],
  ["kk-wave-sawtooth", "wave sawtooth"],
  ["kk-wave-sine", "wave sine"],
  ["kk-wave-square", "wave square"],
  ["kk-wave-triangle", "wave triangle"],
  ["kk-waveform", "waveform"],
  ["kk-waveform-slash", "waveform slash"],
  ["kk-waves", "waves"],
  ["kk-webcam", "webcam"],
  ["kk-webcam-slash", "webcam slash"],
  ["kk-webhooks-logo", "webhooks logo"],
  ["kk-wechat-logo", "wechat logo"],
  ["kk-whatsapp-logo", "whatsapp logo"],
  ["kk-wheelchair", "wheelchair"],
  ["kk-wheelchair-motion", "wheelchair motion"],
  ["kk-wifi-high", "wifi high"],
  ["kk-wifi-low", "wifi low"],
  ["kk-wifi-medium", "wifi medium"],
  ["kk-wifi-none", "wifi none"],
  ["kk-wifi-slash", "wifi slash"],
  ["kk-wifi-x", "wifi x"],
  ["kk-wind", "wind"],
  ["kk-windmill", "windmill"],
  ["kk-windows-logo", "windows logo"],
  ["kk-wine", "wine"],
  ["kk-wrench", "wrench"],
  ["kk-x", "x"],
  ["kk-x-circle", "x circle"],
  ["kk-x-logo", "x logo"],
  ["kk-x-square", "x square"],
  ["kk-yarn", "yarn"],
  ["kk-yin-yang", "yin yang"],
  ["kk-youtube-logo", "youtube logo"],
];

const WEIGHTS = ["regular", "thin", "light", "bold", "fill", "duotone"];

function weightClass(weight) {
  return weight === "regular" ? "" : `kk-${weight}`;
}

export const Explorer = {
  name: "Icon Explorer (interactive)",
  argTypes: {
    icon: {
      control: "select",
      options: ICONS.map(([cls]) => cls),
      description: "Pilih salah satu dari 1.512 ikon yang tersedia",
    },
    weight: {
      control: "select",
      options: WEIGHTS,
    },
    size: {
      control: "select",
      options: ["h-4 w-4", "h-5 w-5", "h-6 w-6", "h-8 w-8", "h-10 w-10", "h-12 w-12"],
    },
  },
  args: {
    icon: "kk-sparkle",
    weight: "regular",
    size: "h-10 w-10",
  },
  render: (args) => {
    const classes = `kk ${args.icon} ${weightClass(args.weight)} ${args.size}`.replace(/\s+/g, " ").trim();
    return `
      <div class="flex flex-col items-center gap-4 p-8">
        <span class="flex h-24 w-24 items-center justify-center rounded-2xl bg-slate-50 text-primary-600">
          <i class="${classes}"></i>
        </span>
        <code class="kbd">&lt;i class="${classes}"&gt;&lt;/i&gt;</code>
      </div>`;
  },
};

export const Library = {
  name: "Library (all 1,512, Regular)",
  render: () => `
    <div class="grid grid-cols-4 gap-4 sm:grid-cols-6 lg:grid-cols-8">
      ${ICONS.map(
        ([cls, label]) => `
        <div class="flex flex-col items-center gap-2">
          <span class="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-50 text-slate-600"><i class="kk ${cls} h-5 w-5"></i></span>
          <p class="text-center text-[11px] text-slate-400">${label}</p>
        </div>`
      ).join("")}
    </div>`,
};

export const Weights = {
  name: "Weights (all 6, one icon)",
  argTypes: {
    icon: { control: "select", options: ICONS.map(([cls]) => cls) },
  },
  args: { icon: "kk-house" },
  render: (args) => `
    <div class="p-6">
      <p class="nav-eyebrow mb-1 px-0">Weights</p>
      <p class="form-hint mb-4 mt-0">Tambahkan satu class modifier di samping <code class="kbd">kk-nama</code> untuk ganti ketebalan — default (tanpa modifier) adalah Regular.</p>
      <div class="grid grid-cols-3 gap-4 sm:grid-cols-6">
        ${WEIGHTS.map(
          (weight) => `
          <div class="flex flex-col items-center gap-2">
            <span class="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-50 text-slate-600"><i class="kk ${args.icon} ${weightClass(weight)} h-6 w-6"></i></span>
            <p class="text-[11px] text-slate-400 capitalize">${weight}</p>
          </div>`
        ).join("")}
      </div>
    </div>`,
};
